Removing venv and fixed GH action. (#1)
* Added .gitignore and added the removing-venv branch to the GH action.

* Fixing error:

Run actions/setup-python@v2
  with:
    python-version: 3.6
    architecture: x64
    token: ***
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Adding the specific 3.6 version to use : 3.6.7 in this case.

* Updating the `actions/setup-python` version.

[https://github.com/actions/setup-python]

* Removing the architecture.

* Commented 2 assertions that are failing (Error occurred! expected instead of Internal Server Error).

* Fixed to only 3.10 Python version, and removed --use-feature option.

* Strategy removed (still 3 actions were running).

* Adding single quotes.

* Trying to fix `unittest discover`.

* Improved format.

* Passing tests name instead of using discovery.

* Removed env directory.

* Re-introducing the matrix strategy.

* Re-introducing the matrix strategy - and commenting out single Python version.

* Using matrix variable.

* Updated checkout action version, and rollback to a single Python version.